# Site information
site_name: Wired! Lab - Tutorial Repository

## To DO - Google Analytics

# Copyright
copyright: '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.'

# Google Analytics
# google_analytics:
#  - 'UA-XXXXXXXX-X'
#  - 'auto'

# Material for MkDocs Theme Configuration
theme:
  name: 'material'
  custom_dir: 'theme'
  palette:
    primary: 'white'
    accent: 'indigo'
  logo: 'images/wired_avatar.svg'
  favicon: 'images/favicon.ico'

extra_css:
  - 'stylesheets/extra.css'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - pymdownx.tasklist:
      custom_checkbox: true

# Page Hierarchy for Nav / TOC
pages:
  - 'index.md'
  - Sketchup:
    - 'Introduction to SketchUp 2018' : 'intro2sketchup/index.md'
  - Omeka:
    - 'Introduction to Omeka' : 'intro2omk/index.md'
  - StoryMapJS:
    - 'StoryMapJS' : 'strympjs/index.md'


